/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sftpupload;

import org.apache.commons.vfs2.*;
import org.apache.commons.vfs2.VFS;
import org.apache.commons.vfs2.provider.sftp.*;
import org.apache.commons.vfs2.impl.*;
import org.apache.commons.vfs2.provider.local.*;
import org.apache.commons.vfs2.provider.sftp.*;
import java.io.File;
import java.net.URI;
import java.util.Arrays;

public class App {
    private DefaultFileSystemManager fsm;
    private String userName = "";
    private String destHost = "";
    private String passWd = "";

    private void sftpInit() throws FileSystemException {
        // fsm.addProvider("sftp", new SftpFileProvider());
        FileSystemManager dfsm = VFS.getManager();
        String[] sarr1 = dfsm.getSchemes();
        System.out.println(Arrays.toString(sarr1));

        // fsm = new DefaultFileSystemManager();
        // fsm.addProvider("file", new DefaultLocalFileProvider());
        // fsm.addProvider("sftp", new SftpFileProvider());
        fsm = (DefaultFileSystemManager) dfsm;
        // fsm.addProvider("sftp", new SftpFileProvider());
        String[] sarr = fsm.getSchemes();
        System.out.println(Arrays.toString(sarr));
    }

    private FileSystemOptions getSftpDefaultOpts() throws FileSystemException {
        FileSystemOptions opts = new FileSystemOptions();

        SftpFileSystemConfigBuilder.getInstance().setStrictHostKeyChecking(opts, "no");
        SftpFileSystemConfigBuilder.getInstance().setUserDirIsRoot(opts, false);
        SftpFileSystemConfigBuilder.getInstance().setSessionTimeoutMillis(opts, 10000);

        return opts;
    }

    private String getSftpRemoteStr(String aRemoteFilePath) {
        String userInfo = userName + ":" + passWd;
        URI uri;
        try {
            uri = new URI("sftp", userInfo, destHost, -1, aRemoteFilePath, null, null);
        } catch (Exception e) {
            System.out.println(e);
            return "";
        }
        return uri.toString();
    }

    private void doWork() {
        FileObject localFile;
        File cmpListFile;
        try {
            File currDir = new File(new File(".").getCanonicalPath());
            cmpListFile = File.createTempFile("ibuilder", "test", currDir);
            localFile = fsm.resolveFile(cmpListFile.getAbsolutePath());
            System.out.println("local file: " + cmpListFile.getAbsolutePath());
            // remote
            FileSystemOptions fileSysOpts = getSftpDefaultOpts();
            FileObject remoteFile = fsm.resolveFile(getSftpRemoteStr("/home/pcheng/OBJ.CL"), fileSysOpts);
            localFile.copyFrom(remoteFile, Selectors.SELECT_SELF);
        } catch (Exception e) {
            System.out.println(e);
        }
    }

    public static void main(String[] args) {
        try {
            App app = new App();
            app.sftpInit();
            app.doWork();
        } catch (Exception e) {
            System.out.println(e);
        }
    }
}
