/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package readbinfile;

import java.io.BufferedInputStream;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.File;
import com.ibm.as400.access.*;

public class App {
    private void readbinfile() {
        try {
            File tmpdir = new File("/tmp");
            File cnvtFile = File.createTempFile("ibuilder", "converted", tmpdir);
            FileOutputStream outst = new FileOutputStream(cnvtFile);
            File tmpfile = new File("/tmp/ibuilder8550289547979706266b");
            BufferedInputStream in = new BufferedInputStream(new FileInputStream(tmpfile));
            byte[] bbuf = new byte[4096];
            int len = 0;
            CharConverter cnvtor = new CharConverter(37);

            System.out.println("source file has " + in.available() + " bytes available");
            while ((len = in.read(bbuf)) != -1) {
                System.out.println("read line: " + len);
                String partstr = cnvtor.byteArrayToString(bbuf, 0, len);
                outst.write(partstr.getBytes());
            }
            outst.close();
        } catch (Exception e) {
            System.out.println(e);
        }
    }

    public static void main(String[] args) {
        App test = new App();
        test.readbinfile();
    }
}
