/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package array.test;

import array.ArrayListTest;
import java.util.Arrays;

public class App {
    private void printArray()
    {
        int[] a = new int[10];
        for (int i = 0; i < a.length; i++) {
            a[i] = i;
        }
        System.out.println(Arrays.toString(a));
    }

    private void copyArray()
    {
        int[] a1 = {2, 3, 5, 7, 11, 13};
        int[] a2 = a1;
        int[] a3;

        if (a2 == a1)
        {
            System.out.println("the same array");
        }
        a3 = Arrays.copyOf(a2, a2.length);
        if (a3 != a2)
        {
            System.out.println("a3 is different from a2");
        }
        int[] a4 = Arrays.copyOf(a3, a3.length * 2);
        System.out.println(Arrays.toString(a4));
    }

    public static void main(String[] args) {
        App app = new App();

        app.printArray();
        app.copyArray();

        ArraysListTest arrtest = new ArrayListTest();
        arrtest.testArrayList();
    }
}
